name: PartyTS
version: 2.0.0
main: me._2818.partyTS.PartyTS
api-version: 1.21
depend: [TimingSystem]
commands:
  party:
    description: Party management commands
    usage: /<command> [create|invite|kick|leave|list]
    aliases: [p]
  duel:
    description: Duel another player in a 1v1 race
    usage: /<command> [player] [laps] [pits]
    aliases: [d]
