name: PartyTS
version: 1.0
main: me._2818.partyTS.PartyTS
api-version: 1.21
depend: [TimingSystem]
resources:
  - 'lang/*.yml'
commands:
  party:
    description: Party management commands
    usage: /<command> [create|invite|kick|leave|list]
    aliases: [p]
  partyrace:
    description: Party race commands
    usage: /<command> [create|finish]
    aliases: [pr]
